---
# tasks file for rke2-install-master

- name: Install RKE2 server on master
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -
  args:
    creates: /usr/local/bin/rke2
  environment:
    INSTALL_RKE2_TYPE: server

- name: Enable and start rke2-server service
  ansible.builtin.systemd:
    name: rke2-server
    enabled: true
    state: started
    daemon_reload: true

