---

- name:  Setup Base Node Packages
  ansible.builtin.import_playbook: playbooks/1Nodes_packages_setup.yaml

- name: Setup RKE2 Cluster Configuration & Install Services
  ansible.builtin.import_playbook: playbooks/2rke2_config_setup.yaml

- name: install kubectl on master nodes and kubeconfig Setup
  ansible.builtin.import_playbook: playbooks/3install_kubectl.yaml