[rke2_servers]
rke2-server-01 ansible_host=172.31.26.158 ansible_connection=local
rke2-server-02 ansible_host=172.31.19.254 ansible_user=ubuntu
rke2-server-03 ansible_host=172.31.21.28  ansible_user=ubuntu

[rke2_agents]
rke2-agent-01 ansible_host=172.31.28.213 ansible_user=ubuntu
rke2-agent-02 ansible_host=172.31.22.229 ansible_user=ubuntu
