---
- name: Base Node Setup
  hosts: all
  become: true
  vars:
    packages:
      - curl
      - jq
      - net-tools
      - ca-certificates
      - gnupg
      - apt-transport-https

  tasks:
    - name: Set system hostname automatically
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Installing required packages
      ansible.builtin.apt:
        update_cache: true
        name: "{{ packages }}"
        state: present

    - name: Checking AppArmor status
      ansible.builtin.command: aa-status
      register: aa_status
      changed_when: false
      failed_when: false
