---
- name: Setup kubectl on RKE2 primary server
  hosts: rke2_servers
  become: true

  tasks:

    - name: Create kubectl symlink
      ansible.builtin.file:
        src: /var/lib/rancher/rke2/bin/kubectl
        dest: /usr/local/bin/kubectl
        state: link
        force: true

    - name: Create .kube directory
      ansible.builtin.file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0700"

    - name: Copy RKE2 kubeconfig
      ansible.builtin.copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: true
        owner: ubuntu
        group: ubuntu
        mode: "0600"